# https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/
image: docker:19.03.15

services:
  - name: docker:19.03.15-dind
    command: ["--insecure-registry=harbor.neko.flab.fujitsu.co.jp:9000"]

variables:
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA
  IMAGE_RELEASE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
  IMAGE_LATEST_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:latest
  DEPLOY_PROJECT_REPOSITORY: http://$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD@harbor.neko.flab.fujitsu.co.jp:10080/$CI_PROJECT_PATH-deploy.git
  DEPLOY_DEV_BRANCH: dev
  KUSTOMIZE_DEV_PATH: overlays/development/
  KUSTOMIZE_PROD_PATH: overlays/production/
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  KUSTOMIZE_GIT_TAG: 3.5.4
  HTTP_PROXY: $http_proxy
  HTTPS_PROXY: $https_proxy

# before_script:
#   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - push
  - deploy

#test:
#  script:
#    - export
    
build:
  stage: build
  script:
    - docker pull $IMAGE_LATEST_TAG || true
    - docker build -t $IMAGE_TAG -t $IMAGE_LATEST_TAG
                   --build-arg http_proxy=$HTTP_PROXY
                   --build-arg https_proxy=$HTTPS_PROXY .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
  except:
    - tags
    
push-tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - tags
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $IMAGE_RELEASE_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_RELEASE_TAG

deproy-prod:
  image: harbor.neko.flab.fujitsu.co.jp:9000/kitajima/kustomize-git:$KUSTOMIZE_GIT_TAG
  variables:
    GIT_STRATEGY: none
  stage: deploy
  only:
    - tags
  script:
    - git clone $DEPLOY_PROJECT_REPOSITORY
    - cd $CI_PROJECT_NAME-deploy
    - git checkout $DEPLOY_DEV_BRANCH
    - cd $KUSTOMIZE_PROD_PATH
    - kustomize edit set image $IMAGE_RELEASE_TAG
    - git config --global user.email "gitlab-runner@gitlab.neko.flab.fujitsu.co.jp"
    - git config --global user.name "gitlab-runner"
    - git add .
    - git commit -m "Update prod service image to $CI_COMMIT_REF_NAME"
    - git push origin $DEPLOY_DEV_BRANCH
